CREATE SET TABLE DP_EDW_PPF.F_PP_BASE_REV_ATTRIBUTION ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP3
     (
      REF_DATE DATE FORMAT 'yyyy-mm-dd',
      MNTHLY_WKLY_FLAG VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ACCS_METH_KEY DECIMAL(18,0),
      ACCNT_KEY INTEGER,
      CUST_KEY INTEGER,
      SCREEN_TYPE VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ROOT_SUBS_KEY DECIMAL(18,0),
      RATEPLAN VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      LINE_START_DATE DATE FORMAT 'yyyy-mm-dd',
      SALES_COHORT_MONTH VARCHAR(5) CHARACTER SET UNICODE NOT CASESPECIFIC,
      TOTAL_REV FLOAT,
      ATL_REV FLOAT,
      BTL_REV FLOAT,
      RGS_30D_REV FLOAT,
      RGS_30_FLAG VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ACTIVE_30_FLAG VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ACTIVE_60_FLAG VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ACTIVE_90_FLAG VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      RGS_30_CU_FLAG VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      OWNERSHIP_CHANGE_FLAG VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PERIOD_END_ACT_FLAG VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      BUNDLE_TYPE VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      BUNDLE_NAME VARCHAR(250) CHARACTER SET LATIN NOT CASESPECIFIC,
      PAYG_TELECOM_REV FLOAT,
      BUNDLE_FREQ_M BYTEINT,
      BUNDLE_RCNCY_M BYTEINT,
      CNT_LAST_4MS_CU INTEGER)
PRIMARY INDEX ( MNTHLY_WKLY_FLAG ,CUST_KEY ,ROOT_SUBS_KEY )
PARTITION BY RANGE_N(REF_DATE  BETWEEN DATE '2015-01-01' AND DATE '2035-12-31' EACH INTERVAL '1' DAY )
INDEX IDX_F_PP_BASE_REV_ATTRIBUTION_2_03 ( ACCS_METH_KEY );



CREATE MULTISET TABLE DP_EDW_PPF.F_PP_PACKAGE_SUBSCRIPTIONS ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP3
     (
      DATA_SOURCE VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      MSISDN VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ACCNT_KEY INTEGER,
      ACCS_METH_KEY DECIMAL(18,0),
      CUST_KEY INTEGER,
      SCREEN_TYPE VARCHAR(3) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PACKAGEX VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PCKG_ID VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      SUBSCRIPTION_START_DT DATE FORMAT 'yyyy-mm-dd',
      SUBSCRIPTION_START_DTTM TIMESTAMP(0),
      SUBSCRIPTION_END_DT DATE FORMAT 'yyyy-mm-dd',
      SUBSCRIPTION_END_DTTM TIMESTAMP(0),
      SUBSCRIPTION_REVENUE DECIMAL(18,2),
      SUBSCRIPTION_CNT INTEGER,
      SYSTEM_RECORD_UID VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      SRC_SYS_INFO_1 VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      SRC_SYS_INFO_2 VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ROOT_SUBS_KEY DECIMAL(18,0),
      RATEPLAN VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CHANNEL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      GIFTER VARCHAR(200) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( CUST_KEY ,PCKG_ID ,ROOT_SUBS_KEY )
PARTITION BY RANGE_N(SUBSCRIPTION_START_DT  BETWEEN DATE '2015-01-01' AND DATE '2035-12-31' EACH INTERVAL '1' DAY )
INDEX IDX_F_PP_PACKAGE_SUBS_03 ( MSISDN );


CREATE SET TABLE DP_EDW_PPF.F_LINE_SALES ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP3
     (
      ORDER_STRT_DT DATE FORMAT 'YY/MM/DD',
      ORDER_END_DT DATE FORMAT 'YY/MM/DD',
      SERVICE_ORDER_NUM VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      ORDER_ID DECIMAL(18,0),
      ACCS_METH_KEY DECIMAL(18,0),
      ACCNT_KEY INTEGER,
      CUST_KEY INTEGER,
      ORDER_TYP_NME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ORDER_SUBTYP_NME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      LINE_TYPE VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      SCREEN_TYPE VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      TECH_SUB_TYPE VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      SERVICE_TYPE VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PROD_KEY INTEGER,
      RATE_PLAN_GRP_NME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      RATE_PLAN_NME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ROOT_SUBS_KEY DECIMAL(18,0),
      SALES_FLAG VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      FIRST_RG_DATE DATE FORMAT 'yyyy-mm-dd')
PRIMARY INDEX ( SERVICE_ORDER_NUM )
INDEX F_LINE_SALES_IDX_01 ( ORDER_END_DT )
INDEX F_LINE_SALES_IDX_02 ( ORDER_STRT_DT )
INDEX F_LINE_SALES_IDX_03 ( CUST_KEY )
INDEX F_LINE_SALES_IDX_04 ( LINE_TYPE )
INDEX F_LINE_SALES_IDX_05 ( SCREEN_TYPE )
INDEX F_LINE_SALES_IDX_06 ( PROD_KEY )
INDEX F_LINE_SALES_IDX_07 ( ORDER_ID )
INDEX F_LINE_SALES_IDX_08 ( ACCS_METH_KEY ,ACCNT_KEY )
INDEX F_LINE_SALES_IDX_09 ( ORDER_END_DT ,SALES_FLAG );


CREATE SET TABLE DP_EDW_PPF.F_LINE_SALES_ATTR ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP3
     (
      SERVICE_ORDER_NUM VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      CUST_AGE INTEGER,
      OLP_PCKG VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      MNP_FROM_OPR VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      SIM_TYPE VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      FIRST_USAGE_DATE DATE FORMAT 'YY/MM/DD',
      EVENT_SOURCE_TYPE_NAME VARCHAR(150) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CHANNEL VARCHAR(150) CHARACTER SET UNICODE NOT CASESPECIFIC,
      SUB_CHANNEL VARCHAR(150) CHARACTER SET UNICODE NOT CASESPECIFIC,
      FIRST_RECHARGE_DATE DATE FORMAT 'YY/MM/DD')
PRIMARY INDEX ( SERVICE_ORDER_NUM );


CREATE SET TABLE DP_EDW_PPF.F_LINE_CHURN ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP3
     (
      ORDER_STRT_DT DATE FORMAT 'yyyy-mm-dd',
      ORDER_END_DT DATE FORMAT 'yyyy-mm-dd',
      SERVICE_ORDER_NUM VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      ORDER_ID DECIMAL(18,0),
      ACCS_METH_KEY DECIMAL(18,0),
      ACCNT_KEY INTEGER,
      CUST_KEY INTEGER,
      ORDER_TYP_NME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ORDER_SUBTYP_NME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      LINE_TYPE VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      SCREEN_TYPE VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      TECH_SUB_TYPE VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      SERVICE_TYPE VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PROD_KEY INTEGER,
      RATE_PLAN_GRP_NME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      RATE_PLAN_NME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ROOT_SUBS_KEY DECIMAL(18,0),
      CHURN_FLAG VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( SERVICE_ORDER_NUM )
INDEX F_LINE_CHURN_IDX_01 ( ORDER_END_DT )
INDEX F_LINE_CHURN_IDX_02 ( ORDER_STRT_DT )
INDEX F_LINE_CHURN_IDX_03 ( CUST_KEY )
INDEX F_LINE_CHURN_IDX_04 ( LINE_TYPE )
INDEX F_LINE_CHURN_IDX_05 ( SCREEN_TYPE )
INDEX F_LINE_CHURN_IDX_06 ( PROD_KEY )
INDEX F_LINE_CHURN_IDX_07 ( ORDER_ID )
INDEX F_LINE_CHURN_IDX_08 ( ACCS_METH_KEY ,ACCNT_KEY )
INDEX F_LINE_CHURN_IDX_09 ( ORDER_END_DT ,CHURN_FLAG );

CREATE SET TABLE DP_EDW_PPF.F_MOBILITY_360 ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP3
     (
      REF_DATE DATE FORMAT 'YY/MM/DD',
      ACCS_METH_VAL VARCHAR(200) CHARACTER SET LATIN NOT CASESPECIFIC,
      ACCS_METH_KEY DECIMAL(18,0),
      ACCNT_NMBR VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      ACCNT_KEY INTEGER,
      LINE_TYPE VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      SCREEN_TYPE VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      TECH_SUB_TYPE VARCHAR(3) CHARACTER SET UNICODE NOT CASESPECIFIC,
      SUBS_PROD_STS_TYP_NM VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ACCNT_STS_TYP_NME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ROOT_SUBS_KEY DECIMAL(18,0),
      LINE_ACTIVATION_DT DATE FORMAT 'YY/MM/DD',
      PROD_NME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CRM_PROD_ID VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CUST_KEY INTEGER,
      CUST_IDENT_NUM VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CUST_BLCKLST_FLG VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      CUST_BLCKLST_STS_NME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      FRST_NME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      LST_NME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      FULL_NME VARCHAR(500) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CUST_IDENT_SUB_TYP_CD VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ID_TYPE VARCHAR(8000) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CUST_VAL_SGMNT_NME VARCHAR(200) CHARACTER SET LATIN NOT CASESPECIFIC,
      CUST_SECT_SGMNT_NME VARCHAR(200) CHARACTER SET LATIN NOT CASESPECIFIC,
      CUST_NAT_CD VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CUST_GENDER_CD VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CUST_BIRTH_DT VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CUST_LANG_CD VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PREVIOUS_RATEPLAN VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      HANDSET_TYPE VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      BRAND_MODEL VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      TAMAYUZ_MEMBERSHIP_TYPE VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      TAMAYUZ_PRIMARY_ACCOUNT BYTEINT,
      FIRST_USAGE_DATE DATE FORMAT 'YY/MM/DD',
      LAST_USAGE_DATE DATE FORMAT 'YY/MM/DD',
      LAST_ROAMING_DATE DATE FORMAT 'YY/MM/DD',
      FIRST_CALL_DATE DATE FORMAT 'YY/MM/DD',
      LAST_SMS_DATE DATE FORMAT 'YY/MM/DD',
      LAST_RECHARGE_DATE DATE FORMAT 'YY/MM/DD',
      LAST_DATA_DATE DATE FORMAT 'YY/MM/DD',
      LAST_CALL_ONNET_DATE DATE FORMAT 'YY/MM/DD',
      LAST_CALL_OFFNET_DATE DATE FORMAT 'YY/MM/DD',
      LAST_CALL_INT_DATE DATE FORMAT 'YY/MM/DD',
      LAST_CALL_DATE DATE FORMAT 'YY/MM/DD',
      LAST_MONTH_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      LAST_3_MONTH_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      LAST_6_MONTH_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      MULTISIM BYTEINT DEFAULT 0 ,
      VOICE_PAYG_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      VOICE_ONNET_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      VOICE_OFFNET_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      VOICE_INTL_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      DATA_PAYG_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      ROAM_PAYG_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      VOICE_OUT_USAGE FLOAT DEFAULT 0.00000000000000E 000 ,
      VOICE_ONNET_OUT_USAGE FLOAT DEFAULT 0.00000000000000E 000 ,
      VOICE_OFFNET_OUT_USAGE FLOAT DEFAULT 0.00000000000000E 000 ,
      VOICE_INTL_OUT_USG FLOAT DEFAULT 0.00000000000000E 000 ,
      DATA_PAYG_USG FLOAT DEFAULT 0.00000000000000E 000 ,
      DATA_USG FLOAT DEFAULT 0.00000000000000E 000 ,
      ROAM_DATA_USG FLOAT DEFAULT 0.00000000000000E 000 ,
      ROAM_PAYG_DATA_USG FLOAT DEFAULT 0.00000000000000E 000 ,
      ROAM_UNDER_PACK_DATA_USG FLOAT DEFAULT 0.00000000000000E 000 ,
      WEEKEND_LAT DECIMAL(18,6),
      WEEKEND_LON DECIMAL(18,6),
      WEEKDAY_LAT DECIMAL(18,6),
      WEEKDAY_LON DECIMAL(18,6),
      BIZ_HOUR_LAT DECIMAL(18,6),
      BIZ_HOUR_LON DECIMAL(18,6),
      NON_BIZ_HOUR_LAT DECIMAL(18,6),
      NON_BIZ_HOUR_LON DECIMAL(18,6),
      OVERALL_LAT FLOAT,
      OVERALL_LON FLOAT,
      Hayy_Name VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      City_Name VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      Governerate_Name VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      Region_Name VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      MASLAHI BYTEINT DEFAULT 0 ,
      VOICE_IN_USG INTEGER DEFAULT 0 ,
      VOICE_IN_ONNET_USG INTEGER DEFAULT 0 ,
      VOICE_IN_ZAIN_USG INTEGER DEFAULT 0 ,
      VOICE_IN_MOBILY_USG INTEGER DEFAULT 0 ,
      VOICE_IN_OTHER_USG INTEGER DEFAULT 0 ,
      LAST_6M_RECHARGE FLOAT DEFAULT 0.00000000000000E 000 ,
      LAST_3M_RECHARGE FLOAT DEFAULT 0.00000000000000E 000 ,
      LAST_1M_RECHARGE FLOAT DEFAULT 0.00000000000000E 000 ,
      MOST_COMPLAINT_TYPE VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      TOTAL_COMPLAINT_CNT INTEGER DEFAULT 0 ,
      BT_RECHARGE DECIMAL(18,4) DEFAULT 0.0000 ,
      ONLINE_RECHARGE DECIMAL(18,4) DEFAULT 0.0000 ,
      STCPAY_RECHARGE DECIMAL(18,4) DEFAULT 0.0000 ,
      VOUCHER_RECHARGE DECIMAL(18,4) DEFAULT 0.0000 ,
      OTHER_RECHARGE DECIMAL(18,4) DEFAULT 0.0000 ,
      VOICE_ROAM_IN_USG FLOAT DEFAULT 0.00000000000000E 000 ,
      VOICE_ROAM_IN_PAYG_USG FLOAT DEFAULT 0.00000000000000E 000 ,
      VOICE_ROAM_IN_UNDER_PACK_USG FLOAT DEFAULT 0.00000000000000E 000 ,
      VOICE_ROAM_OUT_USG FLOAT DEFAULT 0.00000000000000E 000 ,
      VOICE_ROAM_OUT_PAYG_USG FLOAT DEFAULT 0.00000000000000E 000 ,
      VOICE_ROAM_OUT_UNDER_PACK_USG FLOAT DEFAULT 0.00000000000000E 000 ,
      SHERIKATI BYTEINT DEFAULT 0 ,
      ATL_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      BTL_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      RG_FLAG BYTEINT DEFAULT 0 ,
      ROAM_PACK_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      DCB_REV FLOAT DEFAULT 0.00000000000000E 000 ,
      RECHARGE_FREQ FLOAT DEFAULT 0.00000000000000E 000 ,
      P_SEGMENT VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      DEVICE_CONTRACT_FLAG BYTEINT DEFAULT 0 ,
      VBS VARCHAR(11) CHARACTER SET UNICODE NOT CASESPECIFIC,
      VBS_BRACKET VARCHAR(11) CHARACTER SET UNICODE NOT CASESPECIFIC,
      AVG_REV_3M FLOAT DEFAULT 0.00000000000000E 000 ,
      ATL_USER_FLAG BYTEINT DEFAULT 0 ,
      BTL_USER_FLAG BYTEINT DEFAULT 0 ,
      BUNDLE_USER_FLAG BYTEINT DEFAULT 0 ,
      CORE_TELECOM_ACTIVITY_FLAG BYTEINT DEFAULT 0 ,
      HIGHEST_ATL VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      HIGHEST_BTL VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      MOST_USED_RCHRG_CHL VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ACTIVE_30_FLAG BYTEINT DEFAULT 0 ,
      LINE_TENURE VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      AGE_B VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      PREV_BRAND_MODEL VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      NO_OF_PAYMENT_DELINQUENCY INTEGER DEFAULT 0 ,
      NEW_DEVICE_FLAG BYTEINT DEFAULT 0 ,
      NEW_MOVER BYTEINT DEFAULT 0 ,
      TIMELINESS_OF_PAYMENT INTEGER,
      LIFESTYLE_SEGMENT VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      FREQ_DROPPED_CALLS INTEGER DEFAULT 0 ,
      CALLS_TO_900 INTEGER DEFAULT 0 ,
      THROUGH_PUT FLOAT,
      FUP BYTEINT DEFAULT 0 )
PRIMARY INDEX ( ACCS_METH_KEY ,ACCNT_KEY )
PARTITION BY RANGE_N(REF_DATE  BETWEEN DATE '2014-01-01' AND DATE '2030-12-31' EACH INTERVAL '1' MONTH )
INDEX IDX_F_MOBILITY_360_01 ( ACCS_METH_VAL ,ACCNT_NMBR ,LINE_TYPE )
INDEX ( REF_DATE ,ACCS_METH_VAL ,LINE_TYPE ,CUST_KEY )
INDEX ( CUST_IDENT_NUM );



CREATE SET TABLE DP_EDW_PPF.D_PP_PACKAGE ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP3
     (
      PCKG_ID VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
      PCKG_TYPE VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      PCKG_SERVICE_TYPE VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      PCKG_NAME VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
      PCKG_DESC VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PCKG_CATEGORY VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PCKG_SUB_CATEGORY VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALIDITY_DUR_TYPE VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALIDITY_AMOUNT FLOAT,
      PRICE FLOAT,
      PCKG_GROUP_1 VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRICE_RANGE VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( PCKG_ID )
INDEX IDX_D_PP_PACKAGE_SIM_TYPE_01 ( PCKG_NAME );



CREATE SET TABLE DP_EDW_PPF.D_PP_PACKAGE_SRC_LKP ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP3
     (
      PCKG_ID VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      SIM_TYPE VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      DATA_SOURCE_SYSTEM VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      DATA_SOURCE_SUB_SYSTEM VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      SRC_SYS_CODE VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      REV_CAPTURED_FLAG VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      REC_START_DT DATE FORMAT 'yyyy-mm-dd',
      REC_END_DT DATE FORMAT 'yyyy-mm-dd',
      PRICE DECIMAL(12,6),
      OLD_PCKG_NAME VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( DATA_SOURCE_SYSTEM ,SRC_SYS_CODE ,REC_START_DT ,
REC_END_DT )
INDEX IDX_D_PP_PACKAGE_SRC_LKP_01 ( PCKG_ID )
INDEX IDX_D_PP_PACKAGE_SRC_LKP_02 ( DATA_SOURCE_SUB_SYSTEM );





REPLACE VIEW DP_EDW_PPF_VEW.V_PP_RGS_CHURN_DLY AS
SELECT A30.REF_DATE + 1 CHURN_DATE,
	Cast('Daily Churn' AS VARCHAR(30)) CATEGORY, 
	CASE WHEN CL.CUST_IDENT_SUB_TYP_NME IN ('S','I') THEN CL.CUST_IDENT_SUB_TYP_NME
        WHEN CL.CUST_IDENT_SUB_TYP_NME = U&'    \062C\0648\0627\0632 \0633\06BA\0631 \0632\0627\0626\0631 \0648 \062F\0628\0644\0648\0645\0627\0633\064A\064A\0646 ' UESCAPE '\' THEN 'P' 
        ELSE 'Others' END ID_TYPE,
	CL.CUST_NAT_CD,
	A30.PROD_NME AS RATEPLAN,
	CASE WHEN RATEPLAN LIKE '%Ziyara%' THEN 'Ziyarah Subscriber' ELSE 'Domestic Subscriber' END DOMESTIC_SUBS_FLAG,
	CASE WHEN A30.RGS_30_FLAG = 'Y' THEN
		CASE WHEN A30.BUNDLE_TYPE IN ('ATL','BTL') THEN A30.BUNDLE_TYPE
			WHEN A30.BUNDLE_TYPE = 'Prorated Bundle Dormant' THEN 'Prorated Bundle Dormant'
			ELSE 'PayG' END ELSE 'NRGS' END BUNDLE_TYPE,
	Coalesce(FLC.ORDER_SUBTYP_NME,'RGS - Soft Churn') CHURN_TYPE,
	A30.CUST_KEY,
	A30.ROOT_SUBS_KEY,
	A30.ACCS_METH_KEY,
    CASE WHEN Coalesce(RA.SALES_COHORT_MONTH,'00') IN ('00','01','02') THEN 'New Sales' 
        WHEN Coalesce(RA.SALES_COHORT_MONTH,'00') NOT IN ('00','01','02') THEN
            CASE WHEN Coalesce(RA.CNT_LAST_4MS_CU,0) = 4 THEN 'Core Base'
                ELSE 'Non-Core Base' END 
        ELSE 'Undefined' END CORE_SEG
FROM (SELECT A.REF_DATE,
		A.ROOT_SUBS_KEY,
		A.ACCS_METH_KEY,
		A.CUST_KEY,
		A.RGS_30_FLAG,
		A.PROD_NME,
		A.BUNDLE_TYPE,
		Coalesce(FLS.FIRST_RG_DATE,DATE '1900-01-01') FRG
	FROM DP_EDW_PPF.F_PP_DAILY_ACTIVE_30 A
		LEFT OUTER JOIN DP_EDW_PPF.F_LINE_SALES FLS ON (FLS.ROOT_SUBS_KEY = A.ROOT_SUBS_KEY)) A30
	INNER JOIN DP_EDW_SMBB_VEW.DBB_CUSTOMER_LATEST CL ON (CL.CUST_KEY = A30.CUST_KEY)
	LEFT OUTER JOIN DP_EDW_PPF.F_LINE_CHURN FLC ON (FLC.ROOT_SUBS_KEY = A30.ROOT_SUBS_KEY
		AND FLC.ORDER_END_DT = A30.REF_DATE + 1
		--AND FLC.CHURN_FLAG = 'Churn'
		)
	LEFT OUTER JOIN DP_EDW_PPF.F_PP_BASE_REV_ATTRIBUTION RA ON (RA.ROOT_SUBS_KEY = A30.ROOT_SUBS_KEY
			AND RA.REF_DATE = Trunc(CHURN_DATE,'MM')-1
			AND RA.MNTHLY_WKLY_FLAG = 'M'
			AND RA.RGS_30_FLAG = 'Y')
WHERE A30.RGS_30_FLAG = 'Y'
	AND Trunc(A30.FRG,'MM') <> Trunc(CHURN_DATE,'MM')
	AND A30.REF_DATE < (SELECT Max(REF_DATE) FROM DP_EDW_PPF.F_PP_DAILY_ACTIVE_30 )
	AND NOT EXISTS (SELECT ROOT_SUBS_KEY
					FROM DP_EDW_PPF.F_PP_DAILY_ACTIVE_30 A30N
					WHERE A30N.ROOT_SUBS_KEY = A30.ROOT_SUBS_KEY
						AND A30N.REF_DATE = A30.REF_DATE + 1
						AND A30N.RGS_30_FLAG = 'Y')
--QUALIFY Row_Number() Over(PARTITION BY A30.REF_DATE, A30.ROOT_SUBS_KEY ORDER BY FLC.ORDER_END_DT DESC, RA.REF_DATE DESC) = 1;;; 





REPLACE VIEW DP_EDW_PPF_VEW.V_PP_RGS_CHURN_MTHLY AS
SELECT Last_Day(RA.REF_DATE + 1) MONTH_END_DATE,
	Cast('Monthly Churn' AS VARCHAR(30)) CATEGORY,
	RA.SCREEN_TYPE,
	CASE WHEN CL.CUST_IDENT_SUB_TYP_NME IN ('S','I') THEN CL.CUST_IDENT_SUB_TYP_NME
        WHEN CL.CUST_IDENT_SUB_TYP_NME = U&'    \062C\0648\0627\0632 \0633\06BA\0631 \0632\0627\0626\0631 \0648 \062F\0628\0644\0648\0645\0627\0633\064A\064A\0646 ' UESCAPE '\' THEN 'P' 
        ELSE 'Others' END ID_TYPE,
	CL.CUST_NAT_CD,
	RA.RATEPLAN,
	RA.LINE_START_DATE,
    CASE WHEN RA.SALES_COHORT_MONTH = 'OLDER' THEN 'OLDER'
    	WHEN Cast(RA.SALES_COHORT_MONTH AS INTEGER) >= 11 THEN 'OLDER'
    	ELSE LPad(Cast(Cast(RA.SALES_COHORT_MONTH AS INTEGER) + 1 AS VARCHAR(2)), 2, '0')
	END SALES_COHORT_MONTH_,
	RA.CNT_LAST_4MS_CU,
	CASE WHEN RA.SALES_COHORT_MONTH IN ('00','01','02') THEN 'New Sales' 
		WHEN RA.SALES_COHORT_MONTH NOT IN ('00','01','02') THEN
			CASE WHEN RA.CNT_LAST_4MS_CU = 4 THEN 'Core Base'
				ELSE 'Non-Core Base' END 
		ELSE '????' END CORE_SEG,
	RA.OWNERSHIP_CHANGE_FLAG,
	CASE WHEN RATEPLAN LIKE '%Ziyara%' THEN 'Ziyarah Subscriber' ELSE 'Domestic Subscriber' END DOMESTIC_SUBS_FLAG,
	Coalesce(FLC.ORDER_SUBTYP_NME,'RGS Soft Churn') CHURN_TYPE,
	CASE WHEN RA.RGS_30_FLAG = 'Y' THEN
		CASE WHEN RA.BUNDLE_TYPE IN ('ATL','BTL','PG Telcom','DCB VAS') THEN RA.BUNDLE_TYPE
			WHEN RA.BUNDLE_TYPE = 'Prorated Bundle Dormant' THEN 'Prorated Bundle Dormant'
			ELSE 'Unknown' END ELSE 'NRGS' END BUNDLE_TYPE,
    CASE WHEN RA.SCREEN_TYPE = 'SS' THEN
        CASE WHEN  Coalesce(RA.TOTAL_REV,0)  <= 25  THEN '6. VLV (0-25)'
                WHEN Coalesce(RA.TOTAL_REV,0) BETWEEN 25 AND 50 THEN '5. LV (25-50)'
                WHEN Coalesce(RA.TOTAL_REV,0) BETWEEN 50 AND 106  THEN '4. MV (50-106)'
                WHEN Coalesce(RA.TOTAL_REV,0) BETWEEN 106 AND 160  THEN '3. MHVB (106-160)'
                WHEN Coalesce(RA.TOTAL_REV,0) BETWEEN 160 AND 225  THEN '2. HV (160-225)'
                WHEN Coalesce(RA.TOTAL_REV,0) > 225 THEN '1. VHV (>225)' END
        ELSE 'NA' END AS VBS,
    CASE WHEN Cast(RA.REF_DATE - Cast(RA.LINE_START_DATE AS DATE) AS INTEGER) < 90 THEN '1. < 3M'
        WHEN Cast(RA.REF_DATE - Cast(RA.LINE_START_DATE AS DATE) AS INTEGER) BETWEEN 90 AND 180 THEN '2. 3-6M'
        WHEN Cast(RA.REF_DATE - Cast(RA.LINE_START_DATE AS DATE) AS INTEGER) BETWEEN 180 AND 360 THEN '3. 6M-12M'
        WHEN Cast(RA.REF_DATE - Cast(RA.LINE_START_DATE AS DATE) AS INTEGER) BETWEEN 360 AND 1080 THEN '4. 1Y-3Y'
        WHEN Cast(RA.REF_DATE - Cast(RA.LINE_START_DATE AS DATE) AS INTEGER) BETWEEN 1080 AND 1800 THEN '5. 3Y-5Y'
        ELSE  '6. > 5Y' END LINE_TENURE,
	RA.CUST_KEY,
	RA.ROOT_SUBS_KEY,
	RA.TOTAL_REV
FROM DP_EDW_PPF.F_PP_BASE_REV_ATTRIBUTION RA
	INNER JOIN DP_EDW_SMBB_VEW.DBB_CUSTOMER_LATEST CL ON (CL.CUST_KEY = RA.CUST_KEY)
	LEFT OUTER JOIN DP_EDW_PPF.F_LINE_CHURN FLC ON (FLC.ROOT_SUBS_KEY = RA.ROOT_SUBS_KEY
				AND Last_Day(FLC.ORDER_END_DT) = Last_Day(RA.REF_DATE + 1)
				--AND FLC.CHURN_FLAG = 'Churn'
				)
WHERE RA.PERIOD_END_ACT_FLAG = 'Y'
	--AND RA.SCREEN_TYPE = 'SS'
	AND RA.RGS_30_FLAG = 'Y'
	AND RA.MNTHLY_WKLY_FLAG = 'M'
	AND RA.REF_DATE < (SELECT Max(REF_DATE) 
						FROM DP_EDW_PPF.F_PP_BASE_REV_ATTRIBUTION 
						WHERE MNTHLY_WKLY_FLAG = 'M') 
	AND NOT EXISTS (SELECT RAN.ROOT_SUBS_KEY
					FROM DP_EDW_PPF.F_PP_BASE_REV_ATTRIBUTION RAN
					WHERE RAN.REF_DATE = Last_Day(RA.REF_DATE + 1)
						AND RAN.ROOT_SUBS_KEY = RA.ROOT_SUBS_KEY
						AND RAN.RGS_30_FLAG = 'Y'
						AND RAN.MNTHLY_WKLY_FLAG = 'M'
						AND RAN.PERIOD_END_ACT_FLAG = 'Y'); 




REPLACE VIEW DP_EDW_PPF_VEW.V_PP_RGS_RECONNECT_DLY AS
SELECT A30.REF_DATE RECONNECT_DATE,
	Cast('Daily Reconnects' AS VARCHAR(30)) CATEGORY, 
	Coalesce(FLSRT.ORDER_SUBTYP_NME,'RGS - Reconnect') RECONNECT_TYPE,
	CASE WHEN CL.CUST_IDENT_SUB_TYP_NME IN ('S','I') THEN CL.CUST_IDENT_SUB_TYP_NME
        WHEN CL.CUST_IDENT_SUB_TYP_NME = U&'    \062C\0648\0627\0632 \0633\06BA\0631 \0632\0627\0626\0631 \0648 \062F\0628\0644\0648\0645\0627\0633\064A\064A\0646 ' UESCAPE '\' THEN 'P' 
        ELSE 'Others' END ID_TYPE,
	CL.CUST_NAT_CD,
	A30.PROD_NME AS RATEPLAN,
	CASE WHEN RATEPLAN LIKE '%Ziyara%' THEN 'Ziyarah Subscriber' ELSE 'Domestic Subscriber' END DOMESTIC_SUBS_FLAG,
	CASE WHEN A30.RGS_30_FLAG = 'Y' THEN
	CASE WHEN A30.BUNDLE_TYPE IN ('ATL','BTL') THEN A30.BUNDLE_TYPE
		WHEN A30.BUNDLE_TYPE = 'Prorated Bundle Dormant' THEN 'Prorated Bundle Dormant'
		ELSE 'PayG' END ELSE 'NRGS' END BUNDLE_TYPE,
	A30.CUST_KEY,
	A30.ROOT_SUBS_KEY,
	A30.ACCS_METH_KEY,
    CASE WHEN Coalesce(RA.SALES_COHORT_MONTH,'00') IN ('00','01','02') THEN 'New Sales' 
        WHEN Coalesce(RA.SALES_COHORT_MONTH,'00') NOT IN ('00','01','02') THEN
            CASE WHEN Coalesce(RA.CNT_LAST_4MS_CU,0) = 4 THEN 'Core Base'
                ELSE 'Non-Core Base' END 
        ELSE 'Undefined' END CORE_SEG
FROM DP_EDW_PPF.F_PP_DAILY_ACTIVE_30 A30
	INNER JOIN DP_EDW_SMBB_VEW.DBB_CUSTOMER_LATEST CL ON (CL.CUST_KEY = A30.CUST_KEY)
	LEFT OUTER JOIN DP_EDW_PPF.F_PP_BASE_REV_ATTRIBUTION RA ON (RA.ROOT_SUBS_KEY = A30.ROOT_SUBS_KEY
			AND RA.REF_DATE <= Trunc(A30.REF_DATE,'MM')-1
			AND RA.MNTHLY_WKLY_FLAG = 'M'
			AND RA.RGS_30_FLAG = 'Y')
	LEFT OUTER JOIN DP_EDW_PPF.F_LINE_SALES FLSRT ON (FLSRT.ROOT_SUBS_KEY = A30.ROOT_SUBS_KEY
			AND FLSRT.FIRST_RG_DATE = A30.REF_DATE
			AND FLSRT.SALES_FLAG <> 'Sales')
WHERE A30.RGS_30_FLAG = 'Y'
	AND A30.REF_DATE > (SELECT Min(REF_DATE) FROM DP_EDW_PPF.F_PP_DAILY_ACTIVE_30) 
	AND NOT EXISTS (SELECT ROOT_SUBS_KEY
					FROM DP_EDW_PPF.F_PP_DAILY_ACTIVE_30 A30P
					WHERE A30P.ROOT_SUBS_KEY = A30.ROOT_SUBS_KEY
						AND A30P.REF_DATE = A30.REF_DATE - 1
						AND A30P.RGS_30_FLAG = 'Y')
	AND NOT EXISTS (SELECT FLS.ROOT_SUBS_KEY
					FROM DP_EDW_PPF.F_LINE_SALES FLS
					WHERE FLS.FIRST_RG_DATE = A30.REF_DATE
						AND FLS.ROOT_SUBS_KEY = A30.ROOT_SUBS_KEY
						AND FLS.SALES_FLAG = 'Sales')
QUALIFY Row_Number() Over(PARTITION BY A30.REF_DATE, A30.ROOT_SUBS_KEY ORDER BY RA.REF_DATE DESC) = 1; 






REPLACE VIEW DP_EDW_PPF_VEW.V_PP_RGS_RECONNET_MTHLY AS
SELECT RA.REF_DATE MONTH_END_DATE,
	Cast('Monthly Reconnect' AS VARCHAR(30)) CATEGORY,
	Coalesce(FLSRT.ORDER_SUBTYP_NME,'RGS - Reconnect') RECONNECT_TYPE,
	RA.SCREEN_TYPE,
	CASE WHEN CL.CUST_IDENT_SUB_TYP_NME IN ('S','I') THEN CL.CUST_IDENT_SUB_TYP_NME
        WHEN CL.CUST_IDENT_SUB_TYP_NME = U&'    \062C\0648\0627\0632 \0633\06BA\0631 \0632\0627\0626\0631 \0648 \062F\0628\0644\0648\0645\0627\0633\064A\064A\0646 ' UESCAPE '\' THEN 'P' 
        ELSE 'Others' END ID_TYPE,
	CL.CUST_NAT_CD,
	RA.RATEPLAN,
	CASE WHEN RATEPLAN LIKE '%Ziyara%' THEN 'Ziyarah Subscriber' ELSE 'Domestic Subscriber' END DOMESTIC_SUBS_FLAG,
	CASE WHEN RA.RGS_30_FLAG = 'Y' THEN
		CASE WHEN RA.BUNDLE_TYPE IN ('ATL','BTL','PG Telcom','DCB VAS') THEN RA.BUNDLE_TYPE
			WHEN RA.BUNDLE_TYPE = 'Prorated Bundle Dormant' THEN 'Prorated Bundle Dormant'
			ELSE 'Unknown' END ELSE 'NRGS' END BUNDLE_TYPE,
	CASE WHEN RA.SALES_COHORT_MONTH IN ('00','01','02') THEN 'New Sales' 
		WHEN RA.SALES_COHORT_MONTH NOT IN ('00','01','02') THEN
			CASE WHEN RA.CNT_LAST_4MS_CU = 4 THEN 'Core Base'
				ELSE 'Non-Core Base' END 
		ELSE '????' END CORE_SEG,
    CASE WHEN RA.SCREEN_TYPE = 'SS' THEN
        CASE WHEN  Coalesce(RA.TOTAL_REV,0)  <= 25  THEN '6. VLV (0-25)'
                WHEN Coalesce(RA.TOTAL_REV,0) BETWEEN 25 AND 50 THEN '5. LV (25-50)'
                WHEN Coalesce(RA.TOTAL_REV,0) BETWEEN 50 AND 106  THEN '4. MV (50-106)'
                WHEN Coalesce(RA.TOTAL_REV,0) BETWEEN 106 AND 160  THEN '3. MHVB (106-160)'
                WHEN Coalesce(RA.TOTAL_REV,0) BETWEEN 160 AND 225  THEN '2. HV (160-225)'
                WHEN Coalesce(RA.TOTAL_REV,0) > 225 THEN '1. VHV (>225)' END
        ELSE 'NA' END AS VBS,
    CASE WHEN Cast(RA.REF_DATE - Cast(RA.LINE_START_DATE AS DATE) AS INTEGER) < 90 THEN '1. < 3M'
        WHEN Cast(RA.REF_DATE - Cast(RA.LINE_START_DATE AS DATE) AS INTEGER) BETWEEN 90 AND 180 THEN '2. 3-6M'
        WHEN Cast(RA.REF_DATE - Cast(RA.LINE_START_DATE AS DATE) AS INTEGER) BETWEEN 180 AND 360 THEN '3. 6M-12M'
        WHEN Cast(RA.REF_DATE - Cast(RA.LINE_START_DATE AS DATE) AS INTEGER) BETWEEN 360 AND 1080 THEN '4. 1Y-3Y'
        WHEN Cast(RA.REF_DATE - Cast(RA.LINE_START_DATE AS DATE) AS INTEGER) BETWEEN 1080 AND 1800 THEN '5. 3Y-5Y'
        ELSE  '6. > 5Y' END LINE_TENURE,
	RA.CUST_KEY,
	RA.ROOT_SUBS_KEY,
	RA.TOTAL_REV
FROM DP_EDW_PPF.F_PP_BASE_REV_ATTRIBUTION RA
	INNER JOIN DP_EDW_SMBB_VEW.DBB_CUSTOMER_LATEST CL ON (CL.CUST_KEY = RA.CUST_KEY)
	LEFT OUTER JOIN DP_EDW_PPF.F_LINE_SALES FLSRT ON (FLSRT.ROOT_SUBS_KEY = RA.ROOT_SUBS_KEY
			AND Last_Day(FLSRT.FIRST_RG_DATE) = RA.REF_DATE
			AND FLSRT.SALES_FLAG <> 'Sales')
WHERE RA.PERIOD_END_ACT_FLAG = 'Y'
	AND RA.SCREEN_TYPE = 'SS'
	AND RA.RGS_30_FLAG = 'Y'
	AND RA.MNTHLY_WKLY_FLAG = 'M'
	AND RA.REF_DATE > (SELECT Min(REF_DATE) 
						FROM DP_EDW_PPF.F_PP_BASE_REV_ATTRIBUTION 
						WHERE MNTHLY_WKLY_FLAG = 'M') 
	AND NOT EXISTS (SELECT RAP.ROOT_SUBS_KEY
					FROM DP_EDW_PPF.F_PP_BASE_REV_ATTRIBUTION RAP
					WHERE RAP.REF_DATE = Trunc(RA.REF_DATE,'MM') - 1
						AND RAP.ROOT_SUBS_KEY = RA.ROOT_SUBS_KEY
						AND RAP.RGS_30_FLAG = 'Y'
						AND RAP.MNTHLY_WKLY_FLAG = 'M'
						AND RAP.PERIOD_END_ACT_FLAG = 'Y')
	AND NOT EXISTS (SELECT ROOT_SUBS_KEY
					FROM DP_EDW_PPF.F_LINE_SALES FLS
					WHERE FLS.ROOT_SUBS_KEY = RA.ROOT_SUBS_KEY
						AND Last_Day(FLS.FIRST_RG_DATE) = RA.REF_DATE
						AND FLS.SALES_FLAG = 'Sales'); 