                                                        Question 1
Question: 
What percentage of the customer base is active, suspended, barred, blocked, inactive, or deleted?

Query:
WITH BASE_SNAPSHOT AS
(
    SELECT
        LAST_DAY(W.CALENDAR_DATE) AS SNAPSHOT_MONTH,
        PSB.ACCS_METH_VAL,
        PSB.ACCNT_NMBR,
        PSB.SCREEN_TYPE,
        CASE
            WHEN PSB.SUBS_PROD_STS_TYP_NM = 'Outgoing Barred' THEN 'Outgoing Barred'
            WHEN PSB.SUBS_PROD_STS_TYP_NM IN ('Service Blocked','Incoming Barred','Suspended') THEN 'Suspended/Blocked'
            ELSE PSB.SUBS_PROD_STS_TYP_NM
        END AS STATUS_CATEGORY
    FROM DP_EDW_PPF.CBU_WEEKS AS W
    INNER JOIN DP_EDW_PPF.F_RM_POSTPAID_BASE AS PSB
      ON W.CALENDAR_DATE BETWEEN CAST(PSB.SUBS_PROD_STS_STRT_DTTM AS DATE)
                             AND CAST(PSB.SUBS_PROD_STS_END_DTTM AS DATE)
    WHERE W.CALENDAR_DATE = DATE '2026-06-30'
      AND PSB.LINE_TYPE = 'PS'
      AND PSB.SCREEN_TYPE IN ('SS', 'LS')
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY LAST_DAY(W.CALENDAR_DATE), PSB.ACCS_METH_VAL, PSB.ACCNT_NMBR
        ORDER BY PSB.SUBS_STRT_DTTM DESC,
                 PSB.SUBS_END_DTTM DESC,
                 PSB.SUBS_PROD_STS_STRT_DTTM DESC,
                 PSB.SUBS_PROD_STS_END_DTTM DESC
    ) = 1
),
STATUS_COUNTS AS
(
    SELECT
        SNAPSHOT_MONTH,
        STATUS_CATEGORY,
        SCREEN_TYPE,
        COUNT(DISTINCT ACCS_METH_VAL) AS LINE_COUNT
    FROM BASE_SNAPSHOT
    GROUP BY 1, 2, 3
),
TOTALS AS
(
    SELECT
        SNAPSHOT_MONTH,
        SCREEN_TYPE,
        SUM(LINE_COUNT) AS TOTAL_LINES
    FROM STATUS_COUNTS
    GROUP BY 1, 2
)
SELECT
    S.SNAPSHOT_MONTH,
    S.SCREEN_TYPE,
    S.STATUS_CATEGORY,
    S.LINE_COUNT,
    T.TOTAL_LINES,
    100.00 * S.LINE_COUNT / NULLIFZERO(T.TOTAL_LINES) AS PCT_OF_BASE
FROM STATUS_COUNTS S
INNER JOIN TOTALS T
  ON S.SNAPSHOT_MONTH = T.SNAPSHOT_MONTH
 AND S.SCREEN_TYPE = T.SCREEN_TYPE
ORDER BY 1, 2, S.LINE_COUNT DESC;


                                                            Quesion 2
Question:
Which product families contribute the most customers and estimated revenue for q2 2026?

Query:
WITH BASE_Q1 AS
(
    SELECT
        LAST_DAY(W.CALENDAR_DATE) AS SNAPSHOT_MONTH,
        PSB.ACCS_METH_VAL,
        PSB.ACCNT_NMBR,
        PSB.SCREEN_TYPE,
        PSB.ROOT_PROD_NAME AS PRODUCT_FAMILY
    FROM DP_EDW_PPF.CBU_WEEKS AS W
    INNER JOIN DP_EDW_PPF.F_RM_POSTPAID_BASE AS PSB
      ON W.CALENDAR_DATE BETWEEN CAST(PSB.SUBS_PROD_STS_STRT_DTTM AS DATE)
                             AND CAST(PSB.SUBS_PROD_STS_END_DTTM AS DATE)
    WHERE W.CALENDAR_DATE BETWEEN DATE '2026-01-01' AND DATE '2026-03-31'
      AND PSB.LINE_TYPE = 'PS'
      AND PSB.SCREEN_TYPE IN ('SS', 'LS')
      AND PSB.SUBS_PROD_STS_TYP_NM NOT IN ('Inactive','DELETED FROM SOURCE','UNKNOWN')
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY LAST_DAY(W.CALENDAR_DATE), PSB.ACCS_METH_VAL, PSB.ACCNT_NMBR
        ORDER BY PSB.SUBS_STRT_DTTM DESC,
                 PSB.SUBS_END_DTTM DESC,
                 PSB.SUBS_PROD_STS_STRT_DTTM DESC,
                 PSB.SUBS_PROD_STS_END_DTTM DESC
    ) = 1
),
BASE_REVENUE AS
(
    SELECT
        B.PRODUCT_FAMILY,
        B.SCREEN_TYPE,
        B.ACCS_METH_VAL,
        B.ACCNT_NMBR,
        SUM(R.TOTAL_LINE_REV) AS TOTAL_LINE_REV,
        SUM(R.LINE_REV_EXCL_DEVICES) AS MOBILITY_REVENUE
    FROM BASE_Q1 B
    INNER JOIN DP_EDW_PPF.F_RM_PS_MTHLY_REV R
      ON B.ACCS_METH_VAL = R.ACCS_METH_NUM
     AND B.ACCNT_NMBR = R.ACCT_NUM
     AND B.SNAPSHOT_MONTH = R.REF_DATE
    WHERE R.REF_DATE BETWEEN DATE '2026-01-01' AND DATE '2026-03-31'
    GROUP BY 1, 2, 3, 4
)
SELECT
    PRODUCT_FAMILY,
    SCREEN_TYPE,
    COUNT(DISTINCT ACCS_METH_VAL) AS UNIQUE_LINES,
    SUM(TOTAL_LINE_REV) AS TOTAL_REVENUE,
    SUM(MOBILITY_REVENUE) AS MOBILITY_REVENUE,
    SUM(TOTAL_LINE_REV) / NULLIFZERO(COUNT(DISTINCT ACCS_METH_VAL)) AS AVG_REVENUE_PER_LINE
FROM BASE_REVENUE
GROUP BY 1, 2
HAVING COUNT(DISTINCT ACCS_METH_VAL) >= 10
ORDER BY TOTAL_REVENUE DESC, PRODUCT_FAMILY, SCREEN_TYPE;



                                                            Question 3
Question:
Is the business growing through new customer acquisition, migrations, transfers, or reconnections for the last 6 months?

Query:
SELECT
    ORDER_TYP_NME AS SALES_TYPE,
    ORDER_SUBTYP_NME AS SUBTYPE,
    COUNT(*) AS TOTAL_ORDER_LINES,
    COUNT(DISTINCT ACCS_METH_VAL) AS UNIQUE_LINES,
    COUNT(DISTINCT ACCNT_NMBR) AS UNIQUE_ACCOUNTS
FROM DP_EDW_PPF.F_RM_PSD_SALES
WHERE ORDER_END_DT BETWEEN DATE '2026-01-16' AND DATE '2026-07-16'
GROUP BY 1, 2
ORDER BY 1, 2;


                                                            Question 4
Question:


