-- Teradata chat-memory schema.
-- Chat tables are stored in DP_EDW_PPF_STG.

CREATE MULTISET TABLE DP_EDW_PPF_STG.SC_PPQA_CHAT_SESSIONS (
    id VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
    title VARCHAR(120) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL DEFAULT 'New chat',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT SC_PPQA_SESSIONS_PK PRIMARY KEY (id)
)
PRIMARY INDEX (id);

CREATE MULTISET TABLE DP_EDW_PPF_STG.SC_PPQA_CHAT_MESSAGES (
    id VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
    session_id VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
    role VARCHAR(16) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
    content CLOB CHARACTER SET UNICODE NOT NULL,
    dry_run BYTEINT NOT NULL DEFAULT 0,
    metadata CLOB CHARACTER SET UNICODE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT SC_PPQA_MESSAGES_PK PRIMARY KEY (id),
    CONSTRAINT SC_PPQA_MSG_SESSION_FK
        FOREIGN KEY (session_id)
        REFERENCES DP_EDW_PPF_STG.SC_PPQA_CHAT_SESSIONS (id),
    CONSTRAINT SC_PPQA_MSG_ROLE_CK
        CHECK (role IN ('user', 'assistant')),
    CONSTRAINT SC_PPQA_MSG_DRY_CK
        CHECK (dry_run IN (0, 1))
)
PRIMARY INDEX (session_id);
