CREATE TABLE IF NOT EXISTS public.SC_PPQA_CHAT_SESSIONS (
    id UUID PRIMARY KEY,
    title TEXT NOT NULL DEFAULT 'New chat',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.SC_PPQA_CHAT_MESSAGES (
    id UUID PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES public.SC_PPQA_CHAT_SESSIONS(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    dry_run BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS SC_IDX_PPQA_CHAT_SESSIONS_UPDATED_AT
    ON public.SC_PPQA_CHAT_SESSIONS (updated_at DESC);

CREATE INDEX IF NOT EXISTS SC_IDX_PPQA_CHAT_MESSAGES_SESSION_CREATED_AT
    ON public.SC_PPQA_CHAT_MESSAGES (session_id, created_at ASC);
